# Generated by Django 4.0.6 on 2022-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0032_alter_about_id_alter_careerclass_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atmosphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='geosciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='mineralresources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='polarenvironments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='polaroceans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='polarscience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
    ]
