# Generated by Django 4.0.6 on 2022-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0035_alter_about_id_alter_atmosphere_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='southern_ocean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='research_example_down_resgran',
            new_name='antarctic',
        ),
        migrations.RenameModel(
            old_name='research_example_down_scientists',
            new_name='arctic',
        ),
        migrations.RenameModel(
            old_name='research_example_down_sp',
            new_name='himalaya',
        ),
    ]
