# Generated by Django 4.0.6 on 2022-08-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0038_alter_about_id_alter_antarctic_id_alter_arctic_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('closingdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='newsclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('closingdate', models.DateField()),
            ],
        ),
    ]
