# Generated by Django 4.0.6 on 2022-08-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0039_eventclass_newsclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventclass',
            name='sno',
            field=models.CharField(max_length=300),
        ),
    ]
