# Generated by Django 4.0.6 on 2022-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0040_alter_eventclass_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsclass',
            name='sno',
            field=models.CharField(max_length=300),
        ),
    ]
