# Generated by Django 4.0.6 on 2022-08-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0043_alter_about_id_alter_antarctic_id_alter_arctic_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
    ]
