# Generated by Django 3.1.14 on 2022-08-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0044_auto_20220808_1242'),
        ('nsidc_app', '0044_dataclass'),
    ]

    operations = [
    ]
