# Generated by Django 4.0.5 on 2022-08-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsidc_app', '0047_webmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataclass',
            name='content',
        ),
        migrations.AddField(
            model_name='dataclass',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
