# Generated by Django 4.1 on 2022-09-03 14:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0053_get_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about", name="content", field=tinymce.models.HTMLField(),
        ),
    ]
