# Generated by Django 4.1 on 2022-09-03 14:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0054_alter_about_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="antarctic", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="arctic", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="atmosphere", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="eventclass", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="expendition", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="geosciences", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="get_help", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="himalaya", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="ict", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="information_services",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="informationresearch",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="management_support",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="mineralresources",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="newsclass", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="polarenvironments",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="polaroceans", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="polarscience", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="research", name="content", field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="researchgrant",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="researchscientist",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="scientificexpedition",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="scientificpublication",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="southern_ocean",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
