# Generated by Django 4.1 on 2022-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0055_about_is_featured_alter_antarctic_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
    ]
