# Generated by Django 4.1 on 2022-09-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0057_management_support_is_featured"),
    ]

    operations = [
        migrations.RemoveField(model_name="about", name="is_featured",),
    ]
