# Generated by Django 4.1 on 2022-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0058_remove_about_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
    ]
