# Generated by Django 4.1 on 2022-09-04 07:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0060_antarctic_is_featured_arctic_is_featured_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="byte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="rit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_No", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("download", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
    ]
