# Generated by Django 4.1 on 2022-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0061_byte_rit_vessel"),
    ]

    operations = [
        migrations.AddField(
            model_name="corigendumclass",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
    ]
