# Generated by Django 4.1 on 2022-09-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0063_alter_about_content_alter_antarctic_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="bytes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("photo_1", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("photo_2", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("photo_3", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("photo_4", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("photo_5", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
    ]
