# Generated by Django 4.1 on 2022-09-05 08:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0064_bytes"),
    ]

    operations = [
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.CharField(max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
    ]
