# Generated by Django 4.1 on 2022-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0065_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="administrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_No", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_No", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="finance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_No", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="procurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_No", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
    ]
