# Generated by Django 4.1 on 2022-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0067_e_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrative",
            name="desk_no",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="administrative",
            name="email_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="finance",
            name="desk_no",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="finance",
            name="email_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="procurement",
            name="desk_no",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="procurement",
            name="email_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
