# Generated by Django 4.1 on 2022-09-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0068_administrative_desk_no_administrative_email_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="byte",),
    ]
