# Generated by Django 4.1 on 2022-09-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0069_delete_byte"),
    ]

    operations = [
        migrations.DeleteModel(name="management_support",),
    ]
