# Generated by Django 4.1 on 2022-09-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0070_delete_management_support"),
    ]

    operations = [
        migrations.RenameModel(old_name="careerclass", new_name="career",),
    ]
