# Generated by Django 4.1 on 2022-09-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0071_rename_careerclass_career"),
    ]

    operations = [
        migrations.RenameModel(old_name="corigendumclass", new_name="corigendum",),
    ]
