# Generated by Django 4.1 on 2022-09-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0073_rename_dataclass_data"),
    ]

    operations = [
        migrations.DeleteModel(name="webmail",),
    ]
