# Generated by Django 4.1 on 2022-09-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0074_delete_webmail"),
    ]

    operations = [
        migrations.DeleteModel(name="scientificPublication",),
    ]
