# Generated by Django 4.1 on 2022-09-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0077_delete_researchscientist"),
    ]

    operations = [
        migrations.DeleteModel(name="procurementclass",),
    ]
