# Generated by Django 4.1 on 2022-09-06 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0078_delete_procurementclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="procurementclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slno", models.CharField(max_length=2)),
                ("tenderno", models.CharField(max_length=200)),
                ("download", models.URLField(blank=True)),
                ("downloadname", models.CharField(blank=True, max_length=300)),
                ("description", models.CharField(max_length=300)),
                (
                    "releasedate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("closingdate", models.DateField()),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
    ]
