# Generated by Django 4.1 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0079_procurementclass"),
    ]

    operations = [
        migrations.DeleteModel(name="expendition",),
    ]
