# Generated by Django 4.1 on 2022-09-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0080_delete_expendition"),
    ]

    operations = [
        migrations.DeleteModel(name="information_services",),
    ]
