# Generated by Django 4.1 on 2022-09-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0081_delete_information_services"),
    ]

    operations = [
        migrations.DeleteModel(name="research",),
    ]
