# Generated by Django 4.1 on 2022-09-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0082_delete_research"),
    ]

    operations = [
        migrations.DeleteModel(name="researchGrant",),
    ]
