# Generated by Django 4.1 on 2022-09-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0084_rename_profile_staff"),
    ]

    operations = [
        migrations.RenameModel(old_name="enquiryclass", new_name="enquiry",),
        migrations.RenameModel(old_name="eventclass", new_name="event",),
        migrations.RenameModel(old_name="panelmentclass", new_name="panelment",),
    ]
