# Generated by Django 4.1 on 2022-09-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "nsidc_app",
            "0085_rename_enquiryclass_enquiry_rename_eventclass_event_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="procurementclass", new_name="eprocurement",),
        migrations.RenameModel(old_name="gemclass", new_name="gem",),
        migrations.RenameModel(old_name="newsclass", new_name="news",),
    ]
