# Generated by Django 4.1 on 2022-09-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0086_rename_procurementclass_eprocurement_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="myclass",),
    ]
