# Generated by Django 4.1 on 2022-09-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0087_delete_myclass"),
    ]

    operations = [
        migrations.RenameModel(old_name="news", new_name="new",),
    ]
