# Generated by Django 4.1 on 2022-09-06 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nsidc_app", "0090_test1_test2"),
    ]

    operations = [
        migrations.AddField(
            model_name="test2",
            name="designation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="test2",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="test2",
            name="test",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
