# Generated by Django 4.1 on 2022-09-10 14:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nsidc_app", "0091_test2_designation_alter_test2_name_alter_test2_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="readmore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                ("is_featured", models.BooleanField(default=True)),
            ],
        ),
    ]
